version: "3.8"
services:
  cover-letter-backend:
    container_name: cover_letter_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OPEN_API_KEY=${OPEN_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
