version: "3.8"
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - OPEN_API_KEY=${OPEN_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
